// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  throw new Error(
    'Missing env.VITE_SUPABASE_URL - Please create a .env file with your Supabase URL.\n' +
    'See SETUP.md or QUICK_SETUP.md for instructions.'
  );
}

if (!SUPABASE_ANON_KEY) {
  throw new Error(
    'Missing env.VITE_SUPABASE_ANON_KEY - Please create a .env file with your Supabase anon key.\n' +
    'Get it from Settings > API in your Supabase dashboard.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});